"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-10

Creates the full baseline schema from the ORM metadata (tables, enum types,
constraints, indexes, and the KB full-text generated column). Subsequent
migrations are autogenerated once a database is reachable.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

# Importing the package registers every model on Base.metadata.
import app.models  # noqa: F401
from app.core.db import Base

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
